//
//  ApiJsonModel+Extra.swift
//
//
//  Created by Miguel de Icaza on 3/24/23.
//

// This file contains manually written extensions for autogenerated model sources.

// Protocol to share features between JFoundryExtensionClass and JFoundryBuiltinClass
public protocol JClassInfo {
    var name: String { get }
    var enums: [JFoundryGlobalEnumElement]? { get }
}

extension JFoundryBuiltinClass: JClassInfo {}
extension JFoundryExtensionAPIClass: JClassInfo {}

// Used to unify the class methods and the utility methods
public protocol MethodDefinition {
    var name: String { get }
    var isConst: Bool { get }
    var isVararg: Bool { get }
    var isStatic: Bool { get }
    var isVirtual: Bool { get }
    var optionalHash: Int? { get }
    var returnValue: JFoundryReturnValue? { get }
    var description: String? { get }
    var arguments: [JFoundryArgument]? { get }
}

extension JFoundryClassMethod: MethodDefinition {
    public var optionalHash: Int? { hash }
}

extension JFoundryUtilityFunction: MethodDefinition {
    public var isConst: Bool { true }
    public var isStatic: Bool { true }
    public var isVirtual: Bool { false }
    public var optionalHash: Int? { hash }
    public var returnValue: JFoundryReturnValue? {
        if let returnType {
            return JFoundryReturnValue (type: returnType, meta: nil)
        } else {
            return nil
        }
    }
}

public protocol TypeWithMeta {
    var type: String {get}
    var meta: JFoundryArgumentMeta? { get }
}

extension JFoundryArgument: TypeWithMeta {}
extension JFoundryReturnValue: TypeWithMeta {}
